### ISSUE TITLE
Example prints non stop, and needs to print new line.

### ISSUE THREAD

**Issue by NicksonYap** [ivanseidel/LinkedList#10]
In the SimpleIntegerList example, add
```C++
 Serial.println(".");
 while(1);
``` 
just before the end of loop.

https://github.com/ivanseidel/LinkedList/blob/master/examples/SimpleIntegerList/SimpleIntegerList.pde#L53

Same goes with ClassList example:
https://github.com/ivanseidel/LinkedList/blob/master/examples/ClassList/ClassList.pde#L78

**Comment by ivanseidel** [comment]
Well noted! Can you please create a Pull-request?
