### ISSUE TITLE
Does not compile with Arduino 1.6.8

### ISSUE THREAD

**Issue by EfstathiosChatzikyriakidis** [ivanseidel/LinkedList#12]
Does not compile with Arduino 1.6.8

Errors are produced since cannot convert 'false' to NULL pointer.

Please fix it.

**Comment by ivanseidel** [comment]
can you paste the entire error?

Thanks

**Comment by diegodorado** [comment]
had the same problem... got it working replacing all pointer assignements to NULL instead of false
