### ISSUE TITLE
Arduino IDE 1.6.9 reports a warning : converting 'false' to pointer type 'ListNode<MyObject*>*' [-Wconversion-null]

### ISSUE THREAD

**Issue by leseigneur** [ivanseidel/LinkedList#16]
MyObject being whatever I try to store.

I believe I have found the culprit and would like to propose a commit, but I have never done that on GitHub and don't even know if I'm allowed to contribute to this project.

Anyway, the proposed fix is : 
file LinkedList.h, method template<typename T> ListNode<T>* LinkedList<T>::getNode(int index)
line 160 : 
```
- return false; 
+ return 0;
```

Shall someone take this in account or is there a way I can propose formally this change ?

**Comment by ivanseidel** [comment]
should be fixed
