### ISSUE TITLE
feature request: clear + free objects

### ISSUE THREAD

**Issue by RyanAveryBSU** [ivanseidel/LinkedList#29]
LinkedList<obj*>* list = new LL(): 

list->clear(true); does a normal clear but also calls delete() on each item in the list. 

An enum of CLEAR_TYPE { DEFAULT = 0, DELETE, FREE } would be nice so if obj it calls delete, if malloc'd char* it calls free.

**Comment by ivanseidel** [comment]
Its a nice suggestion, but maybe the default behavior of pointers not being destructed is the best for who wants more controll over it.
